language: java

jdk:
  - openjdk8

sudo: false

install: true

cache:
  directories:
    - '$HOME/.m2'
    
notifications:
  email: false
    
script: 
  - export TZ=Asia/Shanghai
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
    
after_success:
  - mvn clean test 
  - bash <(curl -s https://codecov.io/bash)
